/**
 * Conformance tests for the SDK DMN parser.
 *
 * Each test parses a specific `.dmn` fixture with the TypeScript parser and
 * deep-compares the result against a golden JSON snapshot generated by the
 * Elixir parser (`scripts/generate-dmn-parser-snapshots.exs`).
 *
 * Fixture directory (relative to the engine project root):
 *   - apps/core_dmn/test/fixtures/dmns/
 */
import { readFileSync, readdirSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

import { parseDmn } from '../../src/index.js';

const PROJECT_ROOT = resolve(__dirname, '../../../../..');
const SNAPSHOT_DIR = resolve(__dirname, 'snapshots/dmn');
const CORE_FIXTURES = join(PROJECT_ROOT, 'apps/core_dmn/test/fixtures/dmns');

function loadFixture(name: string): string {
  return readFileSync(join(CORE_FIXTURES, `${name}.dmn`), 'utf-8');
}

function loadSnapshot(name: string): unknown {
  return JSON.parse(readFileSync(join(SNAPSHOT_DIR, `${name}.json`), 'utf-8'));
}

function sortKeys(value: unknown): unknown {
  if (value === null || value === undefined) {
    return value;
  }
  if (Array.isArray(value)) {
    return value.map(sortKeys);
  }
  if (typeof value === 'object') {
    const sorted: Record<string, unknown> = {};
    for (const key of Object.keys(value as Record<string, unknown>).sort()) {
      sorted[key] = sortKeys((value as Record<string, unknown>)[key]);
    }
    return sorted;
  }
  return value;
}

/**
 * Keys that exist only in the Elixir model (precompiler artefacts, runtime
 * indices) and must be stripped from snapshots before comparison.
 */
const ELIXIR_ONLY_KEYS = new Set(['compiledInputValuesRef', 'compiledDefaultRef', 'ruleIndex']);

/**
 * Normalizes parser output for cross-parser comparison.
 *
 * Intentional structural differences:
 * 1. `rawXml` — TS includes it, Elixir generator strips it
 * 2. `outputLabel` on decisions — TS derives it from `variable.name`
 *    when present; Elixir only reads the XML `outputLabel` attribute.
 *    When a `variable` is present, we strip `outputLabel` from both
 *    sides since the canonical name lives in `variable.name`.
 * 3. `dmndi` — TS always emits the field (null when absent); Elixir
 *    snapshot generator does not serialize DMNDI at all. Strip from
 *    both sides for comparison.
 * 4. `compiledInputValuesRef`, `compiledDefaultRef`, `ruleIndex` — Elixir
 *    precompiler artefacts that the TS parser does not produce.
 * 5. BKM function definition expressionLanguage: Elixir serializes as
 *    `type` (lowercase), TS uses `kind` (uppercase). Normalize both to
 *    a canonical `_expressionKind` key with lowercase value.
 */
function normalizeForConformance(value: unknown): unknown {
  if (value === null || value === undefined) {
    return value;
  }
  if (Array.isArray(value)) {
    return value.map(normalizeForConformance);
  }
  if (typeof value === 'object') {
    const record = value as Record<string, unknown>;
    const result: Record<string, unknown> = {};
    for (const [key, val] of Object.entries(record)) {
      if (key === 'rawXml') {
        continue;
      }
      if (key === 'dmndi') {
        continue;
      }
      if (ELIXIR_ONLY_KEYS.has(key)) {
        continue;
      }
      if (key === 'outputLabel' && record['variable'] != null) {
        continue;
      }
      if ((key === 'type' || key === 'kind') && 'formalParameters' in record) {
        result['_expressionKind'] = String(val).toLowerCase();
        continue;
      }
      result[key] = normalizeForConformance(val);
    }
    return result;
  }
  return value;
}

function expectConformance(fixtureName: string): void {
  const xml = loadFixture(fixtureName);
  const result = parseDmn(xml);
  const expected = loadSnapshot(fixtureName);

  expect(sortKeys(normalizeForConformance(result))).toEqual(sortKeys(normalizeForConformance(expected)));
}

function snapshotNames(): string[] {
  try {
    return readdirSync(SNAPSHOT_DIR)
      .filter((file) => file.endsWith('.json'))
      .map((file) => file.replace(/\.json$/, ''))
      .sort();
  } catch {
    return [];
  }
}

// ---------------------------------------------------------------------------
// Phase 3 — Decision Tables (basic hit policies)
// ---------------------------------------------------------------------------

describe('decision tables', () => {
  it('simple_unique — UNIQUE hit policy', () => {
    expectConformance('simple_unique');
  });

  it('all_hit_policies — all 7 hit policies in one model', () => {
    expectConformance('all_hit_policies');
  });

  it('collect_with_sum — COLLECT with SUM aggregation', () => {
    expectConformance('collect_with_sum');
  });

  it('multi_input_first — multi-input FIRST hit policy', () => {
    expectConformance('multi_input_first');
  });

  it('multi_output_rule_order — multi-output RULE_ORDER', () => {
    expectConformance('multi_output_rule_order');
  });

  it('priority_hit_policy — PRIORITY', () => {
    expectConformance('priority_hit_policy');
  });

  it('any_same_output — ANY hit policy (same output)', () => {
    expectConformance('any_same_output');
  });

  it('unique_violation — overlapping UNIQUE rules', () => {
    expectConformance('unique_violation');
  });

  it('literal_expression — standalone literal expression', () => {
    expectConformance('literal_expression');
  });

  it('with_input_data — decision with inputData elements', () => {
    expectConformance('with_input_data');
  });

  it('mixed_decisions — multiple decisions (table + literal)', () => {
    expectConformance('mixed_decisions');
  });

  it('decision_with_variable — decision with <variable> child', () => {
    expectConformance('decision_with_variable');
  });
});

// ---------------------------------------------------------------------------
// Phase 4 — DRD Chaining
// ---------------------------------------------------------------------------

describe('DRD chaining', () => {
  it('drg_linear_chain — two-decision dependency chain', () => {
    expectConformance('drg_linear_chain');
  });

  it('drg_diamond — diamond dependency (shared upstream)', () => {
    expectConformance('drg_diamond');
  });

  it('drg_three_level — three-level decision dependency', () => {
    expectConformance('drg_three_level');
  });

  it('drg_cycle — cyclic decision dependencies', () => {
    expectConformance('drg_cycle');
  });
});

// ---------------------------------------------------------------------------
// Phase 4 — Business Knowledge Models
// ---------------------------------------------------------------------------

describe('business knowledge models', () => {
  it('bkm_with_decision_table — BKM with decision table body', () => {
    expectConformance('bkm_with_decision_table');
  });

  it('bkm_with_literal_expression — BKM with literal expression body', () => {
    expectConformance('bkm_with_literal_expression');
  });

  it('bkm_invocation_table — decision invoking BKM (table)', () => {
    expectConformance('bkm_invocation_table');
  });

  it('bkm_invocation_literal — decision invoking BKM (literal)', () => {
    expectConformance('bkm_invocation_literal');
  });

  it('bkm_chain — BKM-to-BKM chaining', () => {
    expectConformance('bkm_chain');
  });

  it('bkm_cycle — cyclic BKM dependencies', () => {
    expectConformance('bkm_cycle');
  });

  it('bkm_missing_reference — decision referencing non-existent BKM', () => {
    expectConformance('bkm_missing_reference');
  });

  it('knowledge_requirement_on_decision — KR on a decision', () => {
    expectConformance('knowledge_requirement_on_decision');
  });

  it('knowledge_requirement_on_bkm — KR on a BKM', () => {
    expectConformance('knowledge_requirement_on_bkm');
  });
});

// ---------------------------------------------------------------------------
// Phase 4 — Knowledge Sources & Authority Requirements
// ---------------------------------------------------------------------------

describe('knowledge sources and authority requirements', () => {
  it('knowledge_source_with_authority — KS with authority requirements', () => {
    expectConformance('knowledge_source_with_authority');
  });

  it('authority_requirement_all_types — all three href types', () => {
    expectConformance('authority_requirement_all_types');
  });
});

// ---------------------------------------------------------------------------
// Phase 4 — Item Definitions
// ---------------------------------------------------------------------------

describe('item definitions', () => {
  it('item_definitions — composite, collection, and simple types', () => {
    expectConformance('item_definitions');
  });
});

// ---------------------------------------------------------------------------
// Phase 4 — Imports
// ---------------------------------------------------------------------------

describe('imports', () => {
  it('import_element — import element at definitions level', () => {
    expectConformance('import_element');
  });

  it('imported_helper — helper model for cross-model imports', () => {
    expectConformance('imported_helper');
  });

  it('importing_model — model importing from another namespace', () => {
    expectConformance('importing_model');
  });

  it('importing_missing — model importing non-existent namespace', () => {
    expectConformance('importing_missing');
  });
});

// ---------------------------------------------------------------------------
// Phase 4 — Comprehensive CL1 Model
// ---------------------------------------------------------------------------

describe('comprehensive', () => {
  it('comprehensive_drd — all CL1 element types in one model', () => {
    expectConformance('comprehensive_drd');
  });
});

// ---------------------------------------------------------------------------
// Phase 6 — CL3 boxed expressions, Decision Services, DMNDI
// ---------------------------------------------------------------------------

describe('CL3 boxed expressions and Decision Services', () => {
  it('boxed_conditional_basic — if/then/else branching', () => {
    expectConformance('boxed_conditional_basic');
  });

  it('boxed_context_basic — context with intermediate entries', () => {
    expectConformance('boxed_context_basic');
  });

  it('boxed_context_nested — nested boxed context', () => {
    expectConformance('boxed_context_nested');
  });

  it('boxed_filter_basic — filter over list', () => {
    expectConformance('boxed_filter_basic');
  });

  it('boxed_invocation_basic — boxed invocation of BKM', () => {
    expectConformance('boxed_invocation_basic');
  });

  it('boxed_iterators — for, every, and some', () => {
    expectConformance('boxed_iterators');
  });

  it('boxed_list_basic — literal list expression', () => {
    expectConformance('boxed_list_basic');
  });

  it('decision_service_basic — Decision Service element', () => {
    expectConformance('decision_service_basic');
  });

  it('decision_service_nested — nested Decision Service', () => {
    expectConformance('decision_service_nested');
  });

  it('function_definition_as_value — function definition as expression body', () => {
    expectConformance('function_definition_as_value');
  });

  it('nested_boxed_multi_type — nested boxed expressions across types', () => {
    expectConformance('nested_boxed_multi_type');
  });

  it('relation_basic — relation expression', () => {
    expectConformance('relation_basic');
  });

  it('with_dmndi — DMNDI diagram interchange preserved', () => {
    expectConformance('with_dmndi');
  });
});

// ---------------------------------------------------------------------------
// Validation edge cases (parser output, not runtime behavior)
// ---------------------------------------------------------------------------

describe('invalid models (parser still produces output)', () => {
  it('invalid_both_expressions — decision with both table and literal', () => {
    expectConformance('invalid_both_expressions');
  });

  it('invalid_no_expression — decision with no value expression', () => {
    expectConformance('invalid_no_expression');
  });

  it('invalid_blank_literal — blank literal expression', () => {
    expectConformance('invalid_blank_literal');
  });

  it('invalid_rule_mismatch — rule entry count mismatch', () => {
    expectConformance('invalid_rule_mismatch');
  });
});

// ---------------------------------------------------------------------------
// Completeness guard: every snapshot file has a test
// ---------------------------------------------------------------------------

describe('snapshot completeness', () => {
  it('every snapshot file has a corresponding test', () => {
    const snapshots = snapshotNames();
    expect(snapshots.length).toBeGreaterThan(0);

    const testedFixtures = new Set<string>();

    for (const name of snapshots) {
      try {
        loadFixture(name);
        loadSnapshot(name);
        testedFixtures.add(name);
      } catch {
        // fixture or snapshot missing — will be caught by individual tests
      }
    }

    const untestedSnapshots = snapshots.filter((name) => !testedFixtures.has(name));
    expect(untestedSnapshots).toEqual([]);
  });
});
