/**
 * Conformance tests for the SDK BPMN parser.
 *
 * Every `.bpmn` fixture is parsed with the TypeScript parser and deep-compared
 * against a golden JSON snapshot generated by the Elixir parser
 * (`scripts/generate-parser-snapshots.exs`). The Elixir parser is the source of
 * truth; a failure here means the TS parser has drifted from it.
 *
 * Fixture directories (relative to the engine project root):
 *   - test/fixtures/bpmns/                 (integration-level fixtures)
 *   - apps/core_bpmn/test/fixtures/bpmns/  (parser-level fixtures)
 *
 * The fixture list is derived from the filesystem, never hand-maintained. A
 * previous revision enumerated fixtures manually and asserted only 76 of 332
 * snapshots; the unasserted remainder silently accumulated parser drift. The
 * `snapshot/fixture coverage` block below fails if the two sets ever diverge,
 * so a snapshot cannot exist without being compared.
 */
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { basename, join, resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

import { parseBpmn } from '../../src/index.js';

const PROJECT_ROOT = resolve(__dirname, '../../../../..');
const SNAPSHOT_DIR = resolve(__dirname, 'snapshots');
const ROOT_FIXTURES = join(PROJECT_ROOT, 'test/fixtures/bpmns');
const CORE_FIXTURES = join(PROJECT_ROOT, 'apps/core_bpmn/test/fixtures/bpmns');

function walk(directory: string, extension: string): string[] {
  let entries: string[];
  try {
    entries = readdirSync(directory);
  } catch {
    return [];
  }

  return entries.flatMap((entry) => {
    const full = join(directory, entry);
    if (statSync(full).isDirectory()) {
      return walk(full, extension);
    }
    return full.endsWith(extension) ? [full] : [];
  });
}

/** Byte-wise comparison, matching how Elixir's `Enum.sort/1` orders binaries. */
function byteCompare(left: string, right: string): number {
  if (left === right) {
    return 0;
  }
  return left < right ? -1 : 1;
}

/**
 * Maps fixture basename to absolute path, mirroring the generator's resolution
 * exactly: it sorts full paths and de-duplicates by basename, keeping the first
 * match. `apps/...` sorts before `test/...`, so CORE_FIXTURES wins a collision.
 * Diverging from that would silently compare a fixture against another file's
 * snapshot.
 */
function buildFixtureIndex(): Map<string, string> {
  const paths = [...walk(ROOT_FIXTURES, '.bpmn'), ...walk(CORE_FIXTURES, '.bpmn')]
    .map((path) => [path.slice(PROJECT_ROOT.length + 1), path] as const)
    .sort(([relativeLeft], [relativeRight]) => byteCompare(relativeLeft, relativeRight));

  const index = new Map<string, string>();
  for (const [, absolute] of paths) {
    const name = basename(absolute, '.bpmn');
    if (!index.has(name)) {
      index.set(name, absolute);
    }
  }
  return index;
}

const FIXTURE_INDEX = buildFixtureIndex();

/**
 * Top level only. `snapshots/dmn/` belongs to `dmn-parser-conformance.test.ts`
 * and has `.dmn` fixtures, not `.bpmn` ones; recursing would drag it in here.
 */
const SNAPSHOT_NAMES = readdirSync(SNAPSHOT_DIR)
  .filter((entry) => entry.endsWith('.json'))
  .map((entry) => basename(entry, '.json'))
  .sort(byteCompare);

function loadSnapshot(name: string): unknown {
  return JSON.parse(readFileSync(join(SNAPSHOT_DIR, `${name}.json`), 'utf-8'));
}

function sortKeys(value: unknown): unknown {
  if (value === null || value === undefined) {
    return value;
  }
  if (Array.isArray(value)) {
    return value.map(sortKeys);
  }
  if (typeof value === 'object') {
    const sorted: Record<string, unknown> = {};
    for (const key of Object.keys(value as Record<string, unknown>).sort()) {
      sorted[key] = sortKeys((value as Record<string, unknown>)[key]);
    }
    return sorted;
  }
  return value;
}

/**
 * Fields that exist only in one parser's output and are stripped during
 * normalization. Every entry here is a channel through which drift can hide,
 * so each must be justified by something the TS parser structurally cannot
 * produce — never by "the TS parser doesn't implement it yet".
 *
 * The `compiled*` fields hold precompiled FEEL references, opaque runtime
 * handles created at deploy time. The two analyses are deploy-time graph
 * analyses performed only by the engine.
 */
const ELIXIR_ONLY_FIELDS = new Set([
  'complexRegionAnalyses',
  'inclusiveJoinAnalyses',
  'compiledCollection',
  'compiledOutputCollection',
  'compiledCompletionCondition',
  'compiledLoopBreakCondition',
  'compiledLoopCondition',
  'activeElementsCompiled',
  'adhocCompletionConditionCompiled',
]);

/**
 * Normalizes parser output for comparison between the TS and Elixir parsers.
 *
 * Intentional structural differences:
 * 1. `rawXml` — TS includes it, the Elixir generator strips it
 * 2. `type` discriminants on `typeData` / `eventDefinition` — TS adds them for
 *    TypeScript discriminated unions; Elixir uses struct names instead
 * 3. `dataStores` / `dataStoreReferences` — TS model includes these; the Elixir
 *    model does not yet expose them
 * 4. `linterScores` — Elixir places these at definitions level, TS at process
 *    level. Both are stripped.
 *
 * A previous revision also reshaped the Elixir snapshot's typed ServiceTask
 * HTTP fields into the TS parser's `serviceTaskTypeConfig` bag. That tolerance
 * is gone: the bag was removed and the TS parser now carries the typed fields.
 */
function normalizeForConformance(value: unknown, isSnapshot = false): unknown {
  if (value === null || value === undefined) {
    return value;
  }
  if (Array.isArray(value)) {
    return value.map((item) => normalizeForConformance(item, isSnapshot));
  }
  if (typeof value === 'object') {
    const record = value as Record<string, unknown>;
    const result: Record<string, unknown> = {};
    for (const [key, val] of Object.entries(record)) {
      if (key === 'rawXml') {
        continue;
      }
      if (key === 'linterScores') {
        continue;
      }
      if (ELIXIR_ONLY_FIELDS.has(key)) {
        continue;
      }
      if (key === 'dataStores' && Array.isArray(val) && val.length === 0) {
        continue;
      }
      if (key === 'dataStoreReferences' && Array.isArray(val) && val.length === 0) {
        continue;
      }
      if (key === 'typeData' && typeof val === 'object' && val !== null) {
        const td = { ...(val as Record<string, unknown>) };
        delete td['type'];
        if (td['eventDefinition'] && typeof td['eventDefinition'] === 'object') {
          const ed = { ...(td['eventDefinition'] as Record<string, unknown>) };
          delete ed['type'];
          td['eventDefinition'] = normalizeForConformance(ed, isSnapshot);
        }
        result[key] = normalizeForConformance(td, isSnapshot);
        continue;
      }
      result[key] = normalizeForConformance(val, isSnapshot);
    }
    return result;
  }
  return value;
}

// ---------------------------------------------------------------------------
// Coverage guards — these are what stop the suite silently shrinking
// ---------------------------------------------------------------------------

describe('snapshot/fixture coverage', () => {
  it('has a fixture for every snapshot', () => {
    const orphaned = SNAPSHOT_NAMES.filter((name) => !FIXTURE_INDEX.has(name));
    expect(orphaned, `Snapshots without a matching .bpmn fixture:\n${orphaned.join('\n')}`).toEqual([]);
  });

  it('has a snapshot for every fixture', () => {
    const known = new Set(SNAPSHOT_NAMES);
    const missing = [...FIXTURE_INDEX.keys()].filter((name) => !known.has(name)).sort();
    expect(
      missing,
      `Fixtures without a snapshot — re-run 'mix run scripts/generate-parser-snapshots.exs':\n${missing.join('\n')}`,
    ).toEqual([]);
  });

  it('compares a non-trivial number of fixtures', () => {
    expect(SNAPSHOT_NAMES.length).toBeGreaterThan(300);
  });
});

// ---------------------------------------------------------------------------
// Conformance — every fixture, derived from the filesystem
// ---------------------------------------------------------------------------

describe('parser conformance', () => {
  it.each(SNAPSHOT_NAMES)('%s matches the Elixir parser', (name) => {
    const fixture = FIXTURE_INDEX.get(name);
    if (fixture === undefined) {
      // Reported by the coverage guard above; skip here to keep the failure
      // signal in one place rather than duplicating it per fixture.
      return;
    }

    const result = parseBpmn(readFileSync(fixture, 'utf-8'));
    const expected = loadSnapshot(name);

    expect(sortKeys(normalizeForConformance(result))).toEqual(sortKeys(normalizeForConformance(expected, true)));
  });
});

