/**
 * Conformance tests for the SDK BPMN parser.
 *
 * Each test parses a specific `.bpmn` fixture with the TypeScript parser and
 * deep-compares the result against a golden JSON snapshot generated by the
 * Elixir parser (`scripts/generate-parser-snapshots.exs`).
 *
 * Fixture directories (relative to the engine project root):
 *   - test/fixtures/bpmns/          (integration-level fixtures)
 *   - apps/core_bpmn/test/fixtures/bpmns/  (parser-level fixtures)
 */
import { readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

import { parseBpmn } from '../../src/index.js';

const PROJECT_ROOT = resolve(__dirname, '../../../../..');
const SNAPSHOT_DIR = resolve(__dirname, 'snapshots');
const ROOT_FIXTURES = join(PROJECT_ROOT, 'test/fixtures/bpmns');
const CORE_FIXTURES = join(PROJECT_ROOT, 'apps/core_bpmn/test/fixtures/bpmns');

function loadFixture(name: string, directory: string = ROOT_FIXTURES): string {
  return readFileSync(join(directory, `${name}.bpmn`), 'utf-8');
}

function loadSnapshot(name: string): unknown {
  return JSON.parse(readFileSync(join(SNAPSHOT_DIR, `${name}.json`), 'utf-8'));
}

function sortKeys(value: unknown): unknown {
  if (value === null || value === undefined) {
    return value;
  }
  if (Array.isArray(value)) {
    return value.map(sortKeys);
  }
  if (typeof value === 'object') {
    const sorted: Record<string, unknown> = {};
    for (const key of Object.keys(value as Record<string, unknown>).sort()) {
      sorted[key] = sortKeys((value as Record<string, unknown>)[key]);
    }
    return sorted;
  }
  return value;
}

const SERVICE_TASK_HANDLER_FIELDS = new Set([
  'httpUrl',
  'httpMethod',
  'httpBody',
  'httpAuthHeader',
  'httpResponseHeaders',
]);

/**
 * Normalizes parser output for comparison between the TS and Elixir parsers.
 *
 * Intentional structural differences:
 * 1. `rawXml` — TS includes it, Elixir generator strips it
 * 2. `type` discriminants on `typeData` / `eventDefinition` — TS adds them for
 *    TypeScript discriminated unions; Elixir uses struct names instead
 * 3. `dataStores` / `dataStoreReferences` — TS model includes these; Elixir
 *    model does not yet expose them
 * 4. ServiceTask handler-specific fields — Elixir stores them as top-level
 *    fields (httpUrl, httpBody, etc.); TS groups them into `serviceTaskTypeConfig`
 */
function normalizeForConformance(value: unknown, isSnapshot = false): unknown {
  if (value === null || value === undefined) {
    return value;
  }
  if (Array.isArray(value)) {
    return value.map((item) => normalizeForConformance(item, isSnapshot));
  }
  if (typeof value === 'object') {
    const record = value as Record<string, unknown>;
    const result: Record<string, unknown> = {};
    for (const [key, val] of Object.entries(record)) {
      if (key === 'rawXml') {
        continue;
      }
      if (key === 'dataStores' && Array.isArray(val) && val.length === 0) {
        continue;
      }
      if (key === 'dataStoreReferences' && Array.isArray(val) && val.length === 0) {
        continue;
      }
      if (key === 'typeData' && typeof val === 'object' && val !== null) {
        const td = { ...(val as Record<string, unknown>) };
        delete td['type'];
        if (td['eventDefinition'] && typeof td['eventDefinition'] === 'object') {
          const ed = { ...(td['eventDefinition'] as Record<string, unknown>) };
          delete ed['type'];
          td['eventDefinition'] = normalizeForConformance(ed, isSnapshot);
        }
        if (isSnapshot) {
          const config: Record<string, unknown> = {};
          for (const field of SERVICE_TASK_HANDLER_FIELDS) {
            if (field in td) {
              if (td[field] !== null) {
                config[field] = td[field];
              }
              delete td[field];
            }
          }
          if (Object.keys(config).length > 0) {
            td['serviceTaskTypeConfig'] = normalizeForConformance(config, isSnapshot);
          } else if ('implementation' in td) {
            td['serviceTaskTypeConfig'] = {};
          }
        }
        result[key] = normalizeForConformance(td, isSnapshot);
        continue;
      }
      result[key] = normalizeForConformance(val, isSnapshot);
    }
    return result;
  }
  return value;
}

function expectConformance(fixtureName: string, directory?: string): void {
  const xml = loadFixture(fixtureName, directory);
  const result = parseBpmn(xml);
  const expected = loadSnapshot(fixtureName);

  expect(sortKeys(normalizeForConformance(result))).toEqual(sortKeys(normalizeForConformance(expected, true)));
}

// ---------------------------------------------------------------------------
// Process Structure
// ---------------------------------------------------------------------------

describe('process structure', () => {
  it('parses a minimal valid process with start and end events', () => {
    expectConformance('minimal_valid', CORE_FIXTURES);
  });

  it('parses a linear start-to-end process', () => {
    expectConformance('linear_start_end');
  });

  it('parses a linear three-node process', () => {
    expectConformance('linear_three_node');
  });

  it('parses chained task sequences', () => {
    expectConformance('chained_tasks');
  });

  it('parses multiple processes in a single definitions element', () => {
    expectConformance('multi_process', CORE_FIXTURES);
  });

  it('parses a process with multiple start events', () => {
    expectConformance('multi_start_events');
  });

  it('parses a process with an implicit sequence flow split', () => {
    expectConformance('implicit_split');
  });

  it('parses a process with a dead-end node (no outgoing flows)', () => {
    expectConformance('dead_end');
  });

  it('preserves dangling references without crashing', () => {
    expectConformance('dangling_refs', CORE_FIXTURES);
  });

  it('parses a process missing the evil:version extension', () => {
    expectConformance('missing_version', CORE_FIXTURES);
  });

  it('parses a process missing a start event', () => {
    expectConformance('missing_start_event', CORE_FIXTURES);
  });
});

// ---------------------------------------------------------------------------
// Exclusive Gateway (XOR)
// ---------------------------------------------------------------------------

describe('exclusive gateway', () => {
  it('parses an XOR split with two condition expressions', () => {
    expectConformance('xor_split_two_conditions');
  });

  it('parses an XOR split with a default flow', () => {
    expectConformance('xor_split_default_flow');
  });

  it('parses an XOR split with no matching condition', () => {
    expectConformance('xor_split_no_match');
  });

  it('parses an XOR split with ambiguous conditions', () => {
    expectConformance('xor_split_ambiguous');
  });

  it('parses a converging XOR join', () => {
    expectConformance('xor_join_converging');
  });

  it('parses an XOR gateway routing to a call activity', () => {
    expectConformance('xor_to_call_activity');
  });
});

// ---------------------------------------------------------------------------
// Service Tasks
// ---------------------------------------------------------------------------

describe('service task', () => {
  it('parses a basic echo service task with implementation attribute', () => {
    expectConformance('service_task_echo');
  });

  it('parses a service task with full pipeline (mappings + contracts)', () => {
    expectConformance('service_task_full_pipeline');
  });

  it('parses a service task with input/output mapper reshaping', () => {
    expectConformance('service_task_mapper_reshapes');
  });

  it('parses a service task with an unknown handler type', () => {
    expectConformance('service_task_unknown_type');
  });

  it('parses an async service task', () => {
    expectConformance('service_task_async');
  });

  it('parses an async service task that fails', () => {
    expectConformance('service_task_async_fail');
  });

  it('parses an async service task that parks', () => {
    expectConformance('service_task_async_park');
  });

  it('parses a service task with a corrupt FEEL input expression', () => {
    expectConformance('service_task_bad_input_feel');
  });

  it('parses a service task with an output contract violation', () => {
    expectConformance('service_task_output_contract_violation');
  });
});

// ---------------------------------------------------------------------------
// User Tasks
// ---------------------------------------------------------------------------

describe('user task', () => {
  it('parses a simple user task', () => {
    expectConformance('user_task_simple');
  });

  it('parses a user task with full pipeline (assignees, form, contracts, mappings)', () => {
    expectConformance('user_task_full_pipeline');
  });

  it('parses a user task with a data contract', () => {
    expectConformance('user_task_with_contract');
  });

  it('parses a user task assigned to a lane', () => {
    expectConformance('user_task_with_lane');
  });

  it('parses a user task with input/output mapper reshaping', () => {
    expectConformance('user_task_output_mapper_reshapes');
  });

  it('parses a user task with a corrupt FEEL input expression', () => {
    expectConformance('user_task_bad_input_feel');
  });

  it('parses a user task with an input contract violation', () => {
    expectConformance('user_task_input_contract_violation');
  });
});

// ---------------------------------------------------------------------------
// Script Tasks
// ---------------------------------------------------------------------------

describe('script task', () => {
  it('parses a script task with an inline FEEL script', () => {
    expectConformance('script_task_inline_feel');
  });

  it('parses a script task with a named script reference', () => {
    expectConformance('script_task_named_ref');
  });

  it('parses a script task with full pipeline (mappings + contracts)', () => {
    expectConformance('script_task_full_pipeline');
  });

  it('parses a script task with a corrupt FEEL expression', () => {
    expectConformance('script_task_corrupt_feel');
  });
});

// ---------------------------------------------------------------------------
// Manual Tasks
// ---------------------------------------------------------------------------

describe('manual task', () => {
  it('parses a manual task with requireConfirmation (wait mode)', () => {
    expectConformance('manual_task_confirm');
  });

  it('parses a passthrough manual task', () => {
    expectConformance('manual_task_passthrough');
  });
});

// ---------------------------------------------------------------------------
// Call Activities
// ---------------------------------------------------------------------------

describe('call activity', () => {
  it('parses a basic call activity with calledElement', () => {
    expectConformance('call_activity_basic');
  });

  it('parses a child process referenced by a call activity', () => {
    expectConformance('call_activity_child');
  });

  it('parses a call activity with an error boundary event', () => {
    expectConformance('call_activity_error_boundary');
  });

  it('parses a call activity referencing a failing child', () => {
    expectConformance('call_activity_failing_child');
  });

  it('parses a call activity without a boundary event (fatal path)', () => {
    expectConformance('call_activity_no_boundary_fatal');
  });

  it('parses a call activity with result output mappings', () => {
    expectConformance('call_activity_result_mapping');
  });

  it('parses a call activity with bad input mappings', () => {
    expectConformance('call_activity_bad_input_mapping');
  });

  it('parses a call activity with bad output mappings', () => {
    expectConformance('call_activity_bad_output_mapping');
  });

  it('parses a resumable child process for call activity', () => {
    expectConformance('call_activity_resume_child');
  });

  it('parses a resumable parent process with call activity', () => {
    expectConformance('call_activity_resume_parent');
  });

  it('parses a resumable parent process with boundary event on call activity', () => {
    expectConformance('call_activity_resume_parent_boundary');
  });

  it('parses a defective resumable child process', () => {
    expectConformance('call_activity_resume_child_defective');
  });

  it('parses a fatal resumable child process', () => {
    expectConformance('call_activity_resume_child_fatal');
  });
});

// ---------------------------------------------------------------------------
// Events
// ---------------------------------------------------------------------------

describe('intermediate events', () => {
  it('parses an intermediate catch event (message)', () => {
    expectConformance('intermediate_catch');
  });
});

describe('link events', () => {
  it('parses basic link throw/catch event pairs', () => {
    expectConformance('link_events_basic');
  });

  it('parses multiple link throw/catch pairs', () => {
    expectConformance('link_events_multi_pair');
  });

  it('parses a duplicate link catch event', () => {
    expectConformance('link_events_duplicate_catch');
  });

  it('parses an orphan link throw event (no matching catch)', () => {
    expectConformance('link_events_orphan_throw');
  });
});

// ---------------------------------------------------------------------------
// Data Objects
// ---------------------------------------------------------------------------

describe('data object', () => {
  it('parses a simple data object write', () => {
    expectConformance('data_object_simple_write');
  });

  it('parses a multi-write data object scenario', () => {
    expectConformance('data_object_multi_write');
  });

  it('parses a shared data object reference', () => {
    expectConformance('data_object_shared_reference');
  });

  it('parses a data object with a FEEL expression', () => {
    expectConformance('data_object_feel_expression');
  });

  it('parses multiple data objects with mixed access patterns', () => {
    expectConformance('data_object_multi_object_mixed_access');
  });

  it('parses a data object with a corrupt FEEL data output association', () => {
    expectConformance('data_object_doa_corrupt_feel');
  });

  it('parses a data object with a passing value contract', () => {
    expectConformance('data_object_value_contract_pass');
  });

  it('parses a data object with a value contract violation', () => {
    expectConformance('data_object_value_contract_violation');
  });

  it('parses a resumable process with data objects', () => {
    expectConformance('data_object_resume');
  });
});
