defmodule BfwEngineWeb.Http.MetricsController do
  @moduledoc "GET /metrics -- Prometheus exposition format."

  use Phoenix.Controller, formats: [:json]

  alias TelemetryMetricsPrometheus.Core, as: PrometheusCore

  @doc "Serves Prometheus exposition format. Disabled state is enforced by `MetricsGatePlug` in the router."
  @spec index(Plug.Conn.t(), map()) :: Plug.Conn.t()
  # False positive: Sobelow cannot see the content type. The body is Prometheus text served as text/plain with nosniff,
  # generated by the telemetry reporter and never from request input, so it is not rendered as HTML.
  # sobelow_skip ["XSS.SendResp"]
  def index(conn, _params) do
    conn
    |> put_resp_content_type("text/plain")
    |> put_resp_header("x-content-type-options", "nosniff")
    |> send_resp(200, PrometheusCore.scrape())
  end
end
